const {
    BAD_REQUEST_STATUS,
    DEFAULT_STATUS_ERR,
    WRONG_TEMPLATE_NAME,
    ACCESS_DENIED,
    EMAIL_ALREADY_EXISTS,
    ENTITY_NOT_FOUND,
    INVALID_TOKEN,
    WRONG_EMAIL_OR_PASSWORD
} = require('./errors.list');

module.exports = {
    ErrorHandler: require('./ErrorHandler'),
    BAD_REQUEST_STATUS,
    DEFAULT_STATUS_ERR,
    WRONG_TEMPLATE_NAME,
    ACCESS_DENIED,
    EMAIL_ALREADY_EXISTS,
    ENTITY_NOT_FOUND,
    INVALID_TOKEN,
    WRONG_EMAIL_OR_PASSWORD,

};
