const { EMAIL_ALREADY_EXISTS,
    UPDATE_UNALLOWED_USER_FIELDS,
    UPDATE_UNALLOWED_POST_FIELDS,
    ACCESS_DENIED,
    ENTITY_NOT_FOUND,
    WRONG_EMAIL_OR_PASSWORD } = require('./errors.list');

module.exports = {
    ErrorHandler: require('./ErrorHandler'),
    EMAIL_ALREADY_EXISTS,
    UPDATE_UNALLOWED_USER_FIELDS,
    UPDATE_UNALLOWED_POST_FIELDS,
    ACCESS_DENIED,
    ENTITY_NOT_FOUND,
    WRONG_EMAIL_OR_PASSWORD
};
