const { FORGOT_PASSWORD, ACTIVATE_ACCOUNT } = require('./action-token-type.enum');
const { MONGO_CONNECT_URL, PORT, FRONT_END_URL, FORGOT_PASSWORD_FRONT_END_URL, ACTIVATE_ACCOUNT_FRONT_END_URL,
    JWT_FORGOT_PASSWORD_SECRET, JWT_ACTIVATE_ACCOUNT_SECRET, JWT_ACCESS_SECRET, JWT_REFRESH_SECRET,
    TRANSPORTER_SENDER_EMAIL, TRANSPORTER_SENDER_PASS } = require('./config');
const { PASSWORD_REGEXP, EMAIL_REGEXP, AUTHORIZATION, CREATED_STATUS, NO_CONTENT_STATUS, BAD_REQUEST_STATUS,
    DEFAULT_STATUS_ERR, WRONG_TEMPLATE_NAME } = require('./constants');
const { CHANGE_USER_PASSWORD, DELETED_USER, REGISTERED_USER, NEW_USER_PASSWORD, UPDATED_USER } = require('./email-actions.enum');
const { ACTION_MODEL, O_AUTH_MODEL, POST_MODEL, USER_MODEL } = require('./model-names.enum');
const { ACCESS, REFRESH } = require('./token-types.enum');

module.exports = {
    emailActionsEnum: require('./email-actions.enum'),
    actionTypes: require('./token-types.enum'),
    userRoles: require('./user-roles.enum'),
    actionTokenTypes: require('./action-token-type.enum'),

    JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET,
    JWT_FORGOT_PASSWORD_SECRET,
    JWT_ACTIVATE_ACCOUNT_SECRET,

    MONGO_CONNECT_URL,
    PORT,
    FRONT_END_URL,
    FORGOT_PASSWORD_FRONT_END_URL,
    ACTIVATE_ACCOUNT_FRONT_END_URL,

    TRANSPORTER_SENDER_EMAIL,
    TRANSPORTER_SENDER_PASS,

    AUTHORIZATION,
    EMAIL_REGEXP,
    PASSWORD_REGEXP,
    CREATED_STATUS,
    NO_CONTENT_STATUS,
    BAD_REQUEST_STATUS,
    DEFAULT_STATUS_ERR,
    WRONG_TEMPLATE_NAME,

    ACCESS,
    REFRESH,
    FORGOT_PASSWORD,
    ACTIVATE_ACCOUNT,

    ACTION_MODEL,
    O_AUTH_MODEL,
    POST_MODEL,
    USER_MODEL,

    CHANGE_USER_PASSWORD,
    DELETED_USER,
    REGISTERED_USER,
    NEW_USER_PASSWORD,
    UPDATED_USER
};
